### ISSUE TITLE
Social login

### ISSUE THREAD

**Issue by TomasKazda** [pslib-cz/2020p3web-ottersdb-MatyasMatura#1]
Implementace není dokončena

**Comment by MatyasMatura** [comment]
Sociální přihlášení přes google by nyní mělo fungovat. 
Stačilo odstranit z .gitignore soubor [launchSettings.json](https://github.com/pslib-cz/2020p3web-ottersdb-MatyasMatura/blob/main/02Vydry/Properties/launchSettings.json), který uchovává informace o portu aplikace.
